import type { Metadata } from "next";
import "./globals.css";
import { BasketStoreProvider } from "@/app/stores/providers/basket-store-provider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <BasketStoreProvider>{children}</BasketStoreProvider>
      </body>
    </html>
  );
}
